name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: jefe-dev-rs
          outputs: dist/snake.svg

      - name: Create output branch if not exists
        run: |
          git fetch
          if git show-ref --verify --quiet refs/heads/output; then
            echo "output branch already exists"
          else
            git checkout --orphan output
            git rm -rf .
            git commit --allow-empty -m "Initialize output branch"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/jefe-dev-rs/jefe-dev-rs.git output
          fi

      - name: Push Snake Animation
        run: |
          git fetch
          git checkout output
          mkdir -p dist
          cp dist/snake.svg dist/snake.svg || echo "File copied"
          git add dist/snake.svg
          git commit -m "Update snake animation" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/jefe-dev-rs/jefe-dev-rs.git output
