name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: jefe-dev-rs
          outputs: dist/snake.svg

      - name: Show dist content (debug)
        run: |
          echo "List dist:"
          ls -la dist || true

      - name: Push snake to output branch (force)
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Ensure we have latest refs
          git fetch origin
          # Force-create/update output branch from current working tree
          git checkout --force -B output
          mkdir -p dist
          # ensure file exists (if not, this will show it in the logs)
          if [ ! -f dist/snake.svg ]; then
            echo "ERROR: dist/snake.svg not found"
            ls -la dist || true
            exit 1
          fi
          git add dist/snake.svg
          git commit -m "Update snake animation" || echo "Nothing to commit"
          git push https://x-access-token:${TOKEN}@github.com/${REPO}.git output --force

